title: Luisa Gonzalez # your name (or website title) here
logo: "/images/IMG_4645.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a dynamic data scientist that empowers businesses and organizations to use data analytics and machine learning to make intelligent and measured decisions.
  <br><br>
  <a href="https://www.linkedin.com/in/luisagonzalezdatascience/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
