title: Luisa Gonzalez # your name (or website title) here
logo: "/images/IMG_4645.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a dynamic data scientist that empowers businesses and organizations to use data analytics and machine learning to make intelligent and measured decisions. Throughout my career, I have had to make difficult decisions on how to best allocate funds and internal resources. Given such hefty responsibility, I always leveraged data and technology to guide me to make enlightened choices. Because data has been a good ally, I decided to delve deeper into the world of data science and to learn how to design and train a wide range of models that can address almost any organizational need. 
  <br><br>
  At the moment, I am working on several machine learning models for a diverse portfolio of clients. One client includes a successful consultant that helps large and midsize business enhance employee retention by building engaging mentoring and sponsorship programming within organizations.  
  <br><br>
  <a href="https://www.linkedin.com/in/luisagonzalezdatascience/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
