title: Luisa Gonzalez # your name (or website title) here
logo: "/images/IMG_4645.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  After leveraging data and technology to make difficult decision on how to allocate funding and resources, I decided to delve deeper into the world of data science and to learn how to design and train a wide range of models that can address almost any business or organizational need.
  <br><br>
  <a href="https://www.linkedin.com/in/luisagonzalezdatascience/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
